/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTunningPlace);
  }
}(this, function (expect, SwaggerTunningPlace) {
  'use strict';

  var instance;
  let orderId;
  const authUtil = require('../common/authentication_utils');
  const constants = require('../../../util/constants');

  beforeEach(function () {
    instance = new SwaggerTunningPlace.OrderApi();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderApi', function () {
    describe('End to End', function () {
      it('Non admin user should add order to cart and list all orders', async function (done) {
        const userToken = await authUtil.loginUser(constants.nonAdminUser.email, constants.nonAdminUser.password);

        await authUtil.setUserToken(instance, userToken, constants.apiAuthenticationName);

        instance.orderAddPartIdPost(constants.partId, function (error, data, res) {
          if (error) throw error;
          orderId = res.body.id;
          instance.orderDetailsIdGet(orderId, function (error, data, res) {
            instance.orderUserGet(function (error, data, res) {
              expect(res.status).to.be(200);
              done();
            });
          });
        });
      });
      it('Non loggedIn user should receive error when try to list all orders', async function (done) {
        const userToken = '';

        await authUtil.setUserToken(instance, userToken, constants.apiAuthenticationName);

        instance.orderUserGet(function (error, data, res) {
          expect(res.status).to.be(401);
          done();
        });
      });
    });
  });
}));
