/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTunningPlace);
  }
}(this, function(expect, SwaggerTunningPlace) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTunningPlace.PartApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PartApi', function() {
    describe('addPart', function() {
      it('should call addPart successfully', function(done) {
        
        //uncomment below and update the code to test addPart
        //instance.addPart(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partAllGet', function() {
      it('should call partAllGet successfully', function(done) {
        //uncomment below and update the code to test partAllGet
        //instance.partAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partDeleteIdDelete', function() {
      it('should call partDeleteIdDelete successfully', function(done) {
        //uncomment below and update the code to test partDeleteIdDelete
        //instance.partDeleteIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partDetailsIdGet', function() {
      it('should call partDetailsIdGet successfully', function(done) {
        //uncomment below and update the code to test partDetailsIdGet
        //instance.partDetailsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('partEditIdPut', function() {
      it('should call partEditIdPut successfully', function(done) {
        //uncomment below and update the code to test partEditIdPut
        //instance.partEditIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
