/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */


(function (root, factory) {

  const jwt = require('jsonwebtoken');
  const encryption = require('../../util/encryption');

  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTunningPlace);
  }
}(this, function (expect, SwaggerTunningPlace) {
  'use strict';
  const authUtil = require('../common/authentication_utils');
  let constants = require('../common/constants');

  var instance;

  beforeEach(function () {
    instance = new SwaggerTunningPlace.ProjectApi();
    instance.apiClient.basePath = constants.basePath;
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectApi', function () {
    describe('End to End', function () {
      it('Authenticated user add project and get details successfully', async function (done) {
        const userToken = await authUtil.loginUser(constants.nonAdminUser.email, constants.nonAdminUser.password);

        await authUtil.setUserToken(instance, userToken, constants.apiAuthenticationName);

        instance.addProject(constants.project, function (error, data, res) {
          if (error) throw error;
          let projectId = res.body.project._id;
          instance.projectDetailsIdGet(projectId, function (error, data, res) {
            if (error) throw error;
            expect(res.status).to.be(200);
            done();
          })
        });
      });
      it('Admin user should be able to CRUD project', async function (done) {
        const userToken = await authUtil.loginUser(constants.adminUser.email, constants.adminUser.password);

        let projectId;
        await authUtil.setUserToken(instance, userToken, constants.apiAuthenticationName);

        instance.addProject(constants.adminProject, function (error, data, res) {
          if (error) throw error;
          projectId = res.body.project._id;
          instance.projectDetailsIdGet(projectId, function (error, data, res) {
            if (error) throw error;
            projectId = res.body.id;

            instance.projectEditIdPut(projectId, constants.newAdminProject, function (error, data, res) {
              projectId = res.body.id;
              instance.projectDeleteIdDelete(projectId, function (error, data, res) {
                expect(res.status).to.be(200);
                done();
              })
            })
          })
        });
      });
    });
  });
}));
