version: '3'
services: 
  app:
    build: .
    environment: 
      DB_PATH: mongodb://mongo:27017/tuning-system
    ports: 
      - '5000:5000'

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'