/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Project', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Project'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerTunningPlace) {
      root.SwaggerTunningPlace = {};
    }
    root.SwaggerTunningPlace.Comment = factory(root.SwaggerTunningPlace.ApiClient, root.SwaggerTunningPlace.Project, root.SwaggerTunningPlace.User);
  }
}(this, function(ApiClient, Project, User) {
  'use strict';




  /**
   * The Comment model module.
   * @module model/Comment
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Comment</code>.
   * @alias module:model/Comment
   * @class
   * @param content {String} 
   * @param projectId {module:model/Project} 
   * @param creatorName {module:model/User} 
   * @param creatorId {module:model/User} 
   */
  var exports = function(content, projectId, creatorName, creatorId) {
    var _this = this;

    _this['content'] = content;
    _this['projectId'] = projectId;
    _this['creatorName'] = creatorName;
    _this['creatorId'] = creatorId;

  };

  /**
   * Constructs a <code>Comment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Comment} obj Optional instance to populate.
   * @return {module:model/Comment} The populated <code>Comment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
      if (data.hasOwnProperty('projectId')) {
        obj['projectId'] = Project.constructFromObject(data['projectId']);
      }
      if (data.hasOwnProperty('creatorName')) {
        obj['creatorName'] = User.constructFromObject(data['creatorName']);
      }
      if (data.hasOwnProperty('creatorId')) {
        obj['creatorId'] = User.constructFromObject(data['creatorId']);
      }
      if (data.hasOwnProperty('createdOn')) {
        obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {String} content
   */
  exports.prototype['content'] = undefined;
  /**
   * @member {module:model/Project} projectId
   */
  exports.prototype['projectId'] = undefined;
  /**
   * @member {module:model/User} creatorName
   */
  exports.prototype['creatorName'] = undefined;
  /**
   * @member {module:model/User} creatorId
   */
  exports.prototype['creatorId'] = undefined;
  /**
   * @member {Date} createdOn
   */
  exports.prototype['createdOn'] = undefined;



  return exports;
}));


