/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Part', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Part'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerTunningPlace) {
      root.SwaggerTunningPlace = {};
    }
    root.SwaggerTunningPlace.Order = factory(root.SwaggerTunningPlace.ApiClient, root.SwaggerTunningPlace.Part, root.SwaggerTunningPlace.User);
  }
}(this, function(ApiClient, Part, User) {
  'use strict';




  /**
   * The Order model module.
   * @module model/Order
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   * @param buyer {module:model/User} 
   * @param part {module:model/Part} 
   */
  var exports = function(buyer, part) {
    var _this = this;

    _this['buyer'] = buyer;
    _this['part'] = part;
  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('buyer')) {
        obj['buyer'] = User.constructFromObject(data['buyer']);
      }
      if (data.hasOwnProperty('part')) {
        obj['part'] = Part.constructFromObject(data['part']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/User} buyer
   */
  exports.prototype['buyer'] = undefined;
  /**
   * @member {module:model/Part} part
   */
  exports.prototype['part'] = undefined;



  return exports;
}));


