/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTunningPlace);
  }
}(this, function(expect, SwaggerTunningPlace) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTunningPlace.Order();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  // describe('Order', function() {
  //   it('should create an instance of Order', function() {
  //     // uncomment below and update the code to test Order
  //     //var instance = new SwaggerTunningPlace.Order();
  //     //expect(instance).to.be.a(SwaggerTunningPlace.Order);
  //   });

  //   it('should have the property buyer (base name: "buyer")', function() {
  //     // uncomment below and update the code to test the property buyer
  //     //var instance = new SwaggerTunningPlace.Order();
  //     //expect(instance).to.be();
  //   });

  //   it('should have the property part (base name: "part")', function() {
  //     // uncomment below and update the code to test the property part
  //     //var instance = new SwaggerTunningPlace.Order();
  //     //expect(instance).to.be();
  //   });

  // });

}));
