/**
 * Swagger Tunning Place
 * This is a sample Tuning Palce server..
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6
 *
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTunningPlace);
  }
}(this, function (expect, SwaggerTunningPlace) {
  'use strict';

  var instance;

  beforeEach(function () {
    instance = new SwaggerTunningPlace.Part(
      "Brakes",
      "Audi",
      2008,
      "Enhanced stopping power",
      250,
      "image"
    );
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Part', function () {
    it('should create an instance of Part', function () {
      // uncomment below and update the code to test Part
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance).to.be.a(SwaggerTunningPlace.Part);
    });

    it('should have the property title (base name: "title")', function () {
      // uncomment below and update the code to test the property title
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.title).to.be("Brakes");
    });

    it('should have the property model (base name: "model")', function () {
      // uncomment below and update the code to test the property model
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.model).to.be("Audi");
    });

    it('should have the property year (base name: "year")', function () {
      // uncomment below and update the code to test the property year
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.year).to.be(2008);
    });

    it('should have the property description (base name: "description")', function () {
      // uncomment below and update the code to test the property description
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.description).to.be("Enhanced stopping power");
    });

    it('should have the property price (base name: "price")', function () {
      // uncomment below and update the code to test the property price
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.price).to.be(250);
    });

    it('should have the property image (base name: "image")', function () {
      // uncomment below and update the code to test the property image
      //var instance = new SwaggerTunningPlace.Part();
      expect(instance.image).to.be("image");
    });

  });

}));
